[development]
address = "192.168.1.5"
port = 8000
log = "normal"
limits = { forms = 32768 }
secret_key = "I6zwdzlm3itGxZ44UBDIyeku/iWp+znCssBpDAbq9hg="
mysql_user = "axel"
mysql_password = "Testing1"
mysql_host = "localhost"
mysql_port = "3306"
mysql_database = "youtube"
stripe_publishable = "pk_test_HCH7T02JK4oEgsBP1NohbMFX"
stripe_secret = "sk_test_cztFtKdeTEnlPLL6DpvkbjFf"
postmark_token = "5f60334c-c829-45c6-aa34-08144c70559c"